# Generated by Django 4.2.6 on 2024-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
