# Generated by Django 4.2.6 on 2024-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salgrade',
            name='lowsal',
            field=models.IntegerField(),
        ),
    ]
